name: CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        channel: [stable, beta, dev]

    steps:
      # Check out the repository
      - uses: actions/checkout@v2

      # Cache dependencies for Dart
      - name: Cache Dart pub dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ matrix.channel }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      # Setup Flutter/Dart with the specific channel
      - name: Setup Dart
        uses: dart-lang/setup-dart@v1

      # Install dependencies
      - name: Install Dependencies
        run: dart pub get

      # Format check
      - name: Dart Format Check
        run: dart format -o none --set-exit-if-changed .

      # Analyze the code
      - name: Dart Analyze
        run: dart analyze
