name: PR Secure Checks

on:
  pull_request_target:
    types: [labeled]

jobs:
  secure-checks:
    if: contains(github.event.pull_request.labels.*.name, 'safe-to-run')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Run Tests with API Key
        env:
          GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}
        run: |
          dart pub global activate coverage
          dart test --coverage=coverage
          dart pub global run coverage:format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib

      # Upload test coverage reports (optional)
      - name: Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: ${{ github.repository }}
          fail_ci_if_error: true
